// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  color_pallete: defineAsyncComponent(() => import("./ColorPallete/index.vue")),
  image_gallery: defineAsyncComponent(() => import("./ImageGallery/index.vue")),
  intro_copy: defineAsyncComponent(() => import("./IntroCopy/index.vue")),
  parallax_img: defineAsyncComponent(() => import("./ParallaxImg/index.vue")),
  rich_text: defineAsyncComponent(() => import("./RichText/index.vue")),
  video_player: defineAsyncComponent(() => import("./VideoPlayer/index.vue")),
});
